export enum SteeringIntent {
    ADVANCE = 'ADVANCE',
    RETREAT = 'RETREAT' ,
    ORBIT_CW = 'ORBIT_CW',
    ORBIT_CCW = 'ORBIT_CCW',
    ORBIT_ADVANCE_CW = 'ORBIT_ADVANCE_CW',
    ORBIT_ADVANCE_CCW = 'ORBIT_ADVANCE_CCW',
    ORBIT_RETREAT_CW = 'ORBIT_RETREAT_CW',
    ORBIT_RETREAT_CCW = 'ORBIT_RETREAT_CCW',
    MAINTAIN_POSITION = 'MAINTAIN_POSITION'
}