export enum SteeringBehaviourType {
    TARGET_SEEK = 'TARGET_SEEK',
    WANDER = 'WANDER',
    OTHER_FACTION_SEEK = 'OTHER_FACTION_SEEK',
    OTHER_FACTION_FLEE = 'OTHER_FACTION_FLEE',
    SELF_FACTION_SEEK = 'SELF_FACTION_SEEK',
    SELF_FACTION_FLEE = 'SELF_FACTION_FLEE',
    ALIGNMENT = 'ALIGNMENT',
    SIMPLE_FORWARDS = 'SIMPLE_FORWARDS',
    AVOID_OBSTACLES = 'AVOID_OBSTACLES',
    CHASE_TARGET = 'CHASE_TARGET'
}