export enum SteeringBehaviourType {
    TARGET_SEEK = 'TARGET_SEEK',
    WANDER = 'WANDER',
    OTHER_FACTION_SEEK = 'OTHER_FACTION_SEEK',
    OTHER_FACTION_FLEE = 'OTHER_FACTION_FLEE',
    SELF_FACTION_SEEK = 'SELF_FACTION_SEEK',
    SELF_FACTION_FLEE = 'SELF_FACTION_FLEE'
}